name: Greeting on variable day

on:
  push:
    branches: [ master ]
#   pull_request:
#     branches: [ master ]

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      - name: "Say Hello Pipeline it's Monday"
        run: echo "$Greeting $First_Name. Today is $DAY_OF_WEEK!"
        env:
          First_Name: MoPipelinena
